// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Collections.Generic;

using Microsoft.EntityFrameworkCore;

using AKF.Common.Models;
using AKF.Database.Interfaces;
using AKF.Database.Context.Configurations;

#nullable disable

namespace AKF.Database.Context
{
    public class DatabaseContext : DbContext, IDatabaseContext
    {
        public DatabaseContext()
        {
        }

        public DatabaseContext(DbContextOptions<DatabaseContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Assessment> Assessments { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Pet> Pets { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<User> Users { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
            
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.ApplyConfiguration(new AssessmentConfiguration());
            modelBuilder.ApplyConfiguration(new PersonConfiguration());
            modelBuilder.ApplyConfiguration(new PetConfiguration());
            modelBuilder.ApplyConfiguration(new StateConfiguration());
        }

        public async Task AddAssessment(Assessment assessment)
        {
            Assessments.Add(assessment);
            await SaveChangesAsync();
        }

        public async Task<Assessment> GetAssessment(long id)
        {
            return await Assessments.Where(a => a.ID == id).FirstOrDefaultAsync();
        }

        public async Task<List<Assessment>> GetAssessments()
        {
            return await Assessments.ToListAsync();
        }

        public async Task<List<Assessment>> GetAssessments(int page, int pageSize)
        {
            return await Assessments.Skip((page - 1) * pageSize).Take(pageSize).ToListAsync();
        }
    }
}
