// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Threading.Tasks;
using System.Collections.Generic;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

using AKF.Database.Models;
using AKF.Database.Interfaces;
using AKF.Database.Context.Configurations;

#nullable disable

namespace AKF.Database.Context
{
    public partial class DatabaseContext : DbContext, IDatabaseContext
    {
        public DatabaseContext()
        {
        }

        public DatabaseContext(DbContextOptions<DatabaseContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Assessment> Assessments { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Pet> Pets { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<User> Users { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.ApplyConfiguration(new AssessmentConfiguration());
            modelBuilder.ApplyConfiguration(new PersonConfiguration());
            modelBuilder.ApplyConfiguration(new PetConfiguration());
            modelBuilder.ApplyConfiguration(new StateConfiguration());
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);

        public async Task AddAssessment(Assessment assessment)
        {
            throw new NotImplementedException();
        }

        public async Task<Assessment> GetAssessment(long id)
        {
            throw new NotImplementedException();
        }

        public async Task<List<Assessment>> GetAssessments()
        {
            throw new NotImplementedException();
        }

        public async Task<List<Assessment>> GetAssessments(int page, int pageSize)
        {
            throw new NotImplementedException();
        }
    }
}
