// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

using AKF.Common.Models;
using AKF.Database.Context;

#nullable disable

namespace AKF.Database.Context.Configurations
{
    public partial class PersonConfiguration : IEntityTypeConfiguration<Person>
    {
        public void Configure(EntityTypeBuilder<Person> entity)
        {
            entity.Property(e => e.AID).HasComment("assessment id");

            entity.HasOne(d => d.AIDNavigation)
                .WithMany(p => p.People)
                .HasForeignKey(d => d.AID)
                .HasConstraintName("FK_Assessments_People");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Person> entity);
    }
}
