// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using AKF.Database.Context;
using AKF.Database.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

#nullable disable

namespace AKF.Database.Context.Configurations
{
    public partial class PetConfiguration : IEntityTypeConfiguration<Pet>
    {
        public void Configure(EntityTypeBuilder<Pet> entity)
        {
            entity.HasOne(d => d.AIDNavigation)
                .WithMany(p => p.Pets)
                .HasForeignKey(d => d.AID)
                .HasConstraintName("FK_Assessments_Pets");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Pet> entity);
    }
}
