// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using AKF.Database.Context;
using AKF.Database.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

#nullable disable

namespace AKF.Database.Context.Configurations
{
    public partial class StateConfiguration : IEntityTypeConfiguration<State>
    {
        public void Configure(EntityTypeBuilder<State> entity)
        {
            entity.Property(e => e.Abbr)
                .IsUnicode(false)
                .IsFixedLength(true);

            entity.Property(e => e.Name).IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<State> entity);
    }
}
