// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable enable

namespace AKF.Database.Models
{
    [Table("Pets", Schema = "lknight1")]
    public partial class Pet
    {
        [Key]
        public int ID { get; set; }
        public int AID { get; set; }
        [Required]
        [StringLength(30)]
        public string Name { get; set; } = default!;
        [Required]
        [StringLength(50)]
        public string Breed { get; set; } = default!;
        public bool IsFriendly { get; set; }
        public byte Location { get; set; }

        [ForeignKey(nameof(AID))]
        [InverseProperty(nameof(Assessment.Pets))]
        public virtual Assessment AIDNavigation { get; set; } = default!;
    }
}